<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MerlinSIP</AssemblyName>
    <RootNamespace>MerlinSip</RootNamespace>
    <Authors>CK Media Services</Authors>
    <Company>Chris Kendall Media</Company>
    <Product>Merlin SIP</Product>
    <Version>1.1.17</Version>
    <AssemblyVersion>1.1.17.0</AssemblyVersion>
    <FileVersion>1.1.17.0</FileVersion>
    <Copyright>Copyright (c) CK Media Services</Copyright>
    <PackageProjectUrl>https://ckmediaservices.co.uk</PackageProjectUrl>
    <ApplicationIcon>Assets\CKMedia-Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Assets\CKMedia-Icon.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\CKMedia-Icon.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="ModernWpfUI" Version="0.9.6" />
    <PackageReference Include="SIPSorcery" Version="10.0.8" />
  </ItemGroup>
</Project>
